/**
 * GitHub-optimized export: structured markdown summary + animated SVG preview.
 *
 * Designed for embedding in PRs, READMEs, and issue comments.
 * The SVG renders natively on GitHub (CSS animations, no JS needed).
 */

import type { ReplaySession, Scene } from "@vibe-replay/types";

// ─── Public API ────────────────────────────────────────────

export interface GitHubFormatOptions {
  /** Full replay URL (gist viewer, self-hosted, etc.) */
  replayUrl?: string;
  /** Relative path to the SVG file (for embedding in markdown) */
  svgPath?: string;
}

/**
 * Generate a GitHub-flavored markdown summary of a replay session.
 * Designed for PR descriptions, issue comments, and READMEs.
 */
export function generateGitHubMarkdown(
  session: ReplaySession,
  opts: GitHubFormatOptions = {},
): string {
  const { meta } = session;
  const phases = extractPhases(session.scenes);
  const filesChanged = collectFilesChanged(session.scenes);
  const toolStats = computeToolStats(session.scenes);
  const duration = formatDuration(meta.stats.durationMs);
  const title = meta.title || meta.slug;

  const lines: string[] = [];

  // ── SVG preview image (clickable link to full replay) ──
  if (opts.svgPath) {
    if (opts.replayUrl) {
      lines.push(`[![AI Session: ${escMd(title)}](${opts.svgPath})](${opts.replayUrl})`);
    } else {
      lines.push(`![AI Session: ${escMd(title)}](${opts.svgPath})`);
    }
    lines.push("");
  }

  // ── Header ──
  lines.push("### AI Coding Session");
  lines.push("");

  // Stats line
  const statParts = [
    duration,
    filesChanged.size > 0 ? `${filesChanged.size} files changed` : null,
    meta.model || null,
  ].filter(Boolean);
  lines.push(statParts.join(" · "));

  // Tool breakdown line
  const toolParts: string[] = [];
  if (toolStats.responses > 0) toolParts.push(`${toolStats.responses} responses`);
  if (toolStats.totalTools > 0) toolParts.push(`${toolStats.totalTools} tools`);
  if (toolStats.thinking > 0) toolParts.push(`${toolStats.thinking} thinking`);
  const breakdownStr = formatToolBreakdown(toolStats);
  if (breakdownStr) {
    lines.push(`${toolParts.join(" · ")} — ${breakdownStr}`);
  } else {
    lines.push(toolParts.join(" · "));
  }
  lines.push("");

  // ── Collapsible body ──
  lines.push("<details>");
  lines.push(
    `<summary>View session details (${meta.stats.userPrompts} prompts, ${meta.stats.toolCalls} tool calls)</summary>`,
  );
  lines.push("");

  for (const phase of phases) {
    lines.push(`> **${escMd(condenseLine(phase.prompt, 120))}**`);
    lines.push("");

    const formatted = formatActionsMarkdown(phase.actions, 8);
    for (const a of formatted) {
      lines.push(`- ${a}`);
    }
    lines.push("");
  }

  // Risk signals
  const risks = detectRiskSignals(session.scenes, filesChanged);
  if (risks.length > 0) {
    lines.push("**Signals:**");
    for (const risk of risks) {
      lines.push(`- ${risk}`);
    }
    lines.push("");
  }

  lines.push("</details>");
  lines.push("");

  // ── Footer ──
  const footerParts = ["Generated by [vibe-replay](https://vibe-replay.com)"];
  if (opts.replayUrl) {
    footerParts.push(`[View full replay →](${opts.replayUrl})`);
  }
  lines.push(`<sub>${footerParts.join(" · ")}</sub>`);
  lines.push("");

  return lines.join("\n");
}

/**
 * Generate an animated SVG preview of a replay session.
 * Renders natively on GitHub (CSS @keyframes animation).
 */
export function generateGitHubSvg(session: ReplaySession, opts: GitHubFormatOptions = {}): string {
  const phases = extractPhases(session.scenes);
  const frames = buildSvgFrames(session, phases, opts);
  return renderSvg(frames, session, opts);
}

// ─── Tool stats breakdown ───────────────────────────────────

interface ToolStats {
  responses: number;
  thinking: number;
  totalTools: number;
  /** Sorted breakdown: [["Read", 26], ["Edit", 52], ...] */
  toolBreakdown: [string, number][];
  /** Unique Bash command names (first word of each command) */
  bashCommands: string[];
}

function computeToolStats(scenes: Scene[]): ToolStats {
  const breakdown: Record<string, number> = {};
  const bashCmds = new Set<string>();
  let responses = 0;
  let thinking = 0;
  let totalTools = 0;

  for (const scene of scenes) {
    if (scene.type === "text-response") {
      responses++;
    } else if (scene.type === "thinking") {
      thinking++;
    } else if (scene.type === "tool-call") {
      totalTools++;
      const name = shortToolName(scene.toolName);
      breakdown[name] = (breakdown[name] || 0) + 1;
      if (scene.toolName === "Bash" && scene.input?.command) {
        const cmd = scene.input.command.trim().split(/[\s|;&]/)[0];
        if (cmd) bashCmds.add(cmd);
      }
    }
  }

  // Sort: common tools first, then by count
  const order = ["Read", "Write", "Edit", "Bash", "Glob", "Grep", "Agent"];
  const entries = Object.entries(breakdown) as [string, number][];
  entries.sort((a, b) => {
    const ai = order.indexOf(a[0]);
    const bi = order.indexOf(b[0]);
    return (ai >= 0 ? ai : 100) - (bi >= 0 ? bi : 100);
  });

  return {
    responses,
    thinking,
    totalTools,
    toolBreakdown: entries,
    bashCommands: [...bashCmds],
  };
}

/** Shorten MCP-style tool names: mcp__service__method → method */
function shortToolName(name: string): string {
  if (name.startsWith("mcp__")) {
    const parts = name.split("__");
    return parts[parts.length - 1];
  }
  return name;
}

/** Format tool breakdown as a single string: "Read 26 · Edit 52 · Bash (git, pnpm) 10" */
function formatToolBreakdown(stats: ToolStats): string {
  return stats.toolBreakdown
    .map(([name, count]) => {
      if (name === "Bash" && stats.bashCommands.length > 0) {
        const cmds = stats.bashCommands.slice(0, 4).join(", ");
        const more = stats.bashCommands.length > 4 ? ", ..." : "";
        return `${name} (${cmds}${more}) ${count}`;
      }
      return `${name} ${count}`;
    })
    .join(" · ");
}

// ─── Phase extraction ──────────────────────────────────────

interface Phase {
  prompt: string;
  actions: GroupedAction[];
}

type GroupedAction =
  | { kind: "read"; files: string[] }
  | { kind: "edit"; file: string }
  | { kind: "create"; file: string }
  | { kind: "run"; command: string; passed: boolean | null }
  | { kind: "search"; description: string }
  | { kind: "text"; summary: string };

function extractPhases(scenes: Scene[]): Phase[] {
  const phases: Phase[] = [];
  let current: { prompt: string; rawActions: RawAction[] } | null = null;

  for (const scene of scenes) {
    if (scene.type === "user-prompt") {
      if (current) {
        phases.push({
          prompt: current.prompt,
          actions: groupActions(current.rawActions),
        });
      }
      current = { prompt: scene.content, rawActions: [] };
      continue;
    }

    if (!current) continue;

    if (scene.type === "tool-call") {
      const action = parseToolCall(scene);
      if (action) current.rawActions.push(action);
    } else if (scene.type === "text-response") {
      // Only include short, meaningful assistant text (not long explanations)
      const text = scene.content.trim();
      if (
        text.length > 10 &&
        text.length <= 150 &&
        !text.startsWith("I'll ") &&
        !text.startsWith("Let me ") &&
        !text.startsWith("I've ") &&
        !text.startsWith("Now ") &&
        !text.startsWith("Sure") &&
        !text.startsWith("OK") &&
        !text.startsWith("Here")
      ) {
        current.rawActions.push({
          kind: "text",
          summary: condenseLine(text, 80),
        });
      }
    }
    // Skip thinking — internal
  }

  if (current) {
    phases.push({
      prompt: current.prompt,
      actions: groupActions(current.rawActions),
    });
  }

  return phases;
}

// ─── Raw action parsing ────────────────────────────────────

interface RawAction {
  kind: "read" | "edit" | "create" | "run" | "search" | "text";
  file?: string;
  command?: string;
  summary?: string;
  passed?: boolean | null;
}

function parseToolCall(scene: Extract<Scene, { type: "tool-call" }>): RawAction | null {
  const { toolName, input, result } = scene;

  switch (toolName) {
    case "Read":
    case "View":
      return { kind: "read", file: baseName(input.file_path || input.path || "") };

    case "Edit":
      return { kind: "edit", file: baseName(input.file_path || "") };

    case "Write":
      return { kind: "create", file: baseName(input.file_path || "") };

    case "Bash": {
      const cmd = (input.command || "").split("\n")[0];
      const lower = result.toLowerCase();
      const failed =
        lower.includes("error") ||
        lower.includes("failed") ||
        lower.includes("fail ") ||
        lower.includes("exit code");
      const passed =
        lower.includes("passed") || lower.includes("success") || lower.includes("all tests");
      return {
        kind: "run",
        command: condenseLine(cmd, 50),
        passed: failed ? false : passed ? true : null,
      };
    }

    case "Glob":
    case "Grep": {
      const pat = input.pattern || input.query || "";
      return {
        kind: "search",
        summary: pat ? `Search \`${condenseLine(pat, 30)}\`` : "Search codebase",
      };
    }

    // Skip internal/noisy tools
    case "TodoWrite":
    case "TodoRead":
    case "Agent":
      return null;

    default:
      return null;
  }
}

function groupActions(raw: RawAction[]): GroupedAction[] {
  const grouped: GroupedAction[] = [];
  let pendingReads: string[] = [];

  const flushReads = () => {
    if (pendingReads.length > 0) {
      grouped.push({ kind: "read", files: [...pendingReads] });
      pendingReads = [];
    }
  };

  for (const action of raw) {
    if (action.kind === "read") {
      if (action.file) pendingReads.push(action.file);
      continue;
    }

    flushReads();

    switch (action.kind) {
      case "edit":
        grouped.push({ kind: "edit", file: action.file! });
        break;
      case "create":
        grouped.push({ kind: "create", file: action.file! });
        break;
      case "run":
        grouped.push({
          kind: "run",
          command: action.command!,
          passed: action.passed ?? null,
        });
        break;
      case "search":
        // Skip consecutive searches
        if (grouped.length === 0 || grouped[grouped.length - 1].kind !== "search") {
          grouped.push({ kind: "search", description: action.summary! });
        }
        break;
      case "text":
        grouped.push({ kind: "text", summary: action.summary! });
        break;
    }
  }

  flushReads();
  return grouped;
}

// ─── Markdown action formatting ────────────────────────────

function formatActionsMarkdown(actions: GroupedAction[], maxLines: number): string[] {
  const lines: string[] = [];

  for (const action of actions) {
    if (lines.length >= maxLines) {
      lines.push(`*... and ${actions.length - maxLines} more actions*`);
      break;
    }

    switch (action.kind) {
      case "read": {
        const show = action.files.slice(0, 5);
        const fileList = show.map((f) => `\`${f}\``).join(", ");
        const more = action.files.length > 5 ? ` +${action.files.length - 5} more` : "";
        lines.push(`Read ${fileList}${more}`);
        break;
      }
      case "edit":
        lines.push(`Edit \`${action.file}\``);
        break;
      case "create":
        lines.push(`Create \`${action.file}\``);
        break;
      case "run": {
        const status =
          action.passed === true ? " — passed" : action.passed === false ? " — **failed**" : "";
        lines.push(`Run \`${action.command}\`${status}`);
        break;
      }
      case "search":
        lines.push(action.description);
        break;
      case "text":
        lines.push(`*${action.summary}*`);
        break;
    }
  }

  return lines;
}

// ─── Risk signals ──────────────────────────────────────────

function detectRiskSignals(scenes: Scene[], filesChanged: Map<string, number>): string[] {
  const risks: string[] = [];

  // Files modified many times (possible struggle)
  for (const [file, count] of filesChanged) {
    if (count >= 4) {
      risks.push(`\`${file}\` modified ${count}x`);
    }
  }

  // Test failures
  let testFailures = 0;
  let testPasses = 0;
  for (const scene of scenes) {
    if (scene.type !== "tool-call" || scene.toolName !== "Bash") continue;
    const cmd = scene.input.command || "";
    const isTest =
      cmd.includes("test") ||
      cmd.includes("jest") ||
      cmd.includes("vitest") ||
      cmd.includes("pytest");
    if (!isTest) continue;
    const r = scene.result.toLowerCase();
    if (r.includes("failed") || r.includes("fail ") || r.includes("error")) {
      testFailures++;
    }
    if (r.includes("passed") || r.includes("success") || r.includes("all tests")) {
      testPasses++;
    }
  }
  if (testFailures > 0) {
    const resolved = testPasses > 0 ? " (resolved)" : "";
    risks.push(`${testFailures} test failure(s)${resolved}`);
  }

  // Compactions
  if (scenes.some((s) => s.type === "compaction-summary")) {
    risks.push("Session was compacted (very long conversation)");
  }

  return risks;
}

// ─── SVG generation ────────────────────────────────────────

// GitHub dark palette — feels native, looks good on both light/dark backgrounds
const C = {
  bg: "#0d1117",
  headerBg: "#161b22",
  border: "#30363d",
  text: "#e6edf3",
  dim: "#7d8590",
  blue: "#58a6ff",
  green: "#3fb950",
  red: "#f85149",
  purple: "#bc8cff",
  orange: "#d29922",
  dotRed: "#ff7b72",
  dotYellow: "#d29922",
  dotGreen: "#3fb950",
};

const SVG_W = 840;
const SVG_H = 380;
const HEADER_H = 36;
const FOOTER_H = 40;
const CONTENT_TOP = HEADER_H + 24;
const MARGIN = 40;
const FONT = `'SF Mono','Cascadia Code','Fira Code',Menlo,Consolas,'Liberation Mono',monospace`;

interface SvgFrame {
  label: string;
  title: string;
  titleLine2?: string;
  lines: SvgTextLine[];
}

interface SvgTextLine {
  text: string;
  color: string;
  bold?: boolean;
}

function buildSvgFrames(
  session: ReplaySession,
  phases: Phase[],
  opts: GitHubFormatOptions = {},
): SvgFrame[] {
  const { meta } = session;
  const frames: SvgFrame[] = [];
  const task = phases[0]?.prompt || meta.title || meta.slug;
  const duration = formatDuration(meta.stats.durationMs);
  const toolStats = computeToolStats(session.scenes);

  // ── Frame 0: Title ──
  const taskWrap = wrapText(task, 56);
  const titleFrame: SvgFrame = {
    label: "TASK",
    title: taskWrap[0],
    titleLine2: taskWrap[1],
    lines: [],
  };
  if (meta.model) {
    titleFrame.lines.push({ text: meta.model, color: C.purple });
  }
  // Tool stats summary line
  const statParts: string[] = [];
  if (toolStats.responses > 0) statParts.push(`${toolStats.responses} responses`);
  if (toolStats.totalTools > 0) statParts.push(`${toolStats.totalTools} tools`);
  if (toolStats.thinking > 0) statParts.push(`${toolStats.thinking} thinking`);
  if (statParts.length > 0) {
    titleFrame.lines.push({ text: statParts.join("  ·  "), color: C.dim });
  }
  // Tool breakdown line
  const breakdown = formatToolBreakdown(toolStats);
  if (breakdown) {
    titleFrame.lines.push({ text: condenseLine(breakdown, 60), color: C.orange });
  }
  const metaLine = [duration, meta.project || meta.cwd].filter(Boolean).join("  ·  ");
  titleFrame.lines.push({ text: metaLine, color: C.dim });
  frames.push(titleFrame);

  // ── Phase frames (pick most interesting, max 3) ──
  const selected = selectKeyPhases(phases, 3);
  for (const phase of selected) {
    const phaseIdx = phases.indexOf(phase) + 1;
    const promptWrap = wrapText(phase.prompt, 52);
    const frame: SvgFrame = {
      label: `STEP ${phaseIdx} OF ${phases.length}`,
      title: promptWrap[0],
      titleLine2: promptWrap[1],
      lines: [],
    };

    let count = 0;
    for (const action of phase.actions) {
      if (count >= 5) {
        frame.lines.push({
          text: `    ... +${phase.actions.length - count} more`,
          color: C.dim,
        });
        break;
      }
      const line = actionToSvgLine(action);
      if (line) {
        frame.lines.push(line);
        count++;
      }
    }
    frames.push(frame);
  }

  // ── Summary frame ──
  const filesChanged = collectFilesChanged(session.scenes);
  const summaryStats = [
    filesChanged.size > 0 ? `${filesChanged.size} files changed` : null,
    `${meta.stats.userPrompts} prompts`,
    duration,
  ]
    .filter(Boolean)
    .join("  ·  ");

  // Summary tool stats
  const summaryToolParts: string[] = [];
  if (toolStats.responses > 0) summaryToolParts.push(`${toolStats.responses} responses`);
  if (toolStats.totalTools > 0) summaryToolParts.push(`${toolStats.totalTools} tools`);
  if (toolStats.thinking > 0) summaryToolParts.push(`${toolStats.thinking} thinking`);

  const summaryLines: SvgTextLine[] = [
    { text: summaryStats, color: C.green },
    { text: summaryToolParts.join("  ·  "), color: C.dim },
    { text: condenseLine(breakdown, 60), color: C.orange },
    { text: "", color: C.dim }, // spacer
  ];
  if (opts.replayUrl) {
    summaryLines.push({ text: "View full replay  →", color: C.blue, bold: true });
  }
  summaryLines.push({ text: "vibe-replay.com", color: C.dim });

  const summaryFrame: SvgFrame = {
    label: "COMPLETE",
    title: meta.title || condenseLine(task, 50),
    lines: summaryLines,
  };
  frames.push(summaryFrame);

  return frames;
}

function selectKeyPhases(phases: Phase[], max: number): Phase[] {
  if (phases.length <= max) return [...phases];

  // Always include first phase
  const selected: Phase[] = [phases[0]];

  // Score remaining phases
  const scored = phases.slice(1).map((p, i) => {
    let score = p.actions.length;
    for (const a of p.actions) {
      if (a.kind === "run" && a.passed === false) score += 5;
      if (a.kind === "run" && a.passed === true) score += 3;
      if (a.kind === "create") score += 2;
    }
    return { phase: p, score, origIdx: i + 1 };
  });

  scored.sort((a, b) => b.score - a.score);
  for (const { phase } of scored.slice(0, max - 1)) {
    selected.push(phase);
  }

  // Maintain original order
  return selected.sort((a, b) => phases.indexOf(a) - phases.indexOf(b));
}

function actionToSvgLine(action: GroupedAction): SvgTextLine | null {
  switch (action.kind) {
    case "read": {
      const show = action.files.slice(0, 3);
      const more = action.files.length > 3 ? ` +${action.files.length - 3}` : "";
      return { text: `    ${show.join(", ")}${more}`, color: C.dim };
    }
    case "edit":
      return { text: `    Edit ${action.file}`, color: C.text };
    case "create":
      return { text: `    + ${action.file}`, color: C.green };
    case "run": {
      const tag = action.passed === true ? "  [ok]" : action.passed === false ? "  [fail]" : "";
      const color = action.passed === true ? C.green : action.passed === false ? C.red : C.text;
      return { text: `    $ ${action.command}${tag}`, color };
    }
    case "search":
      return null; // too noisy for SVG
    case "text":
      return {
        text: `    ${condenseLine(action.summary, 48)}`,
        color: C.dim,
      };
  }
}

function renderSvg(
  frames: SvgFrame[],
  session: ReplaySession,
  opts: GitHubFormatOptions = {},
): string {
  const N = frames.length;
  const secPerFrame = 5;
  const cycleDuration = N * secPerFrame;

  // Each frame occupies 1/N of the cycle
  const pct = 100 / N;
  // Fade transitions as percentage of total cycle
  const fadeIn = (0.5 / cycleDuration) * 100; // 0.5s fade
  const holdEnd = pct - fadeIn;
  const fadeOut = pct;

  // Per-frame animation classes — frame-0 starts visible (no blank flash)
  const animClasses = frames
    .map((_, i) => {
      const delay = i * secPerFrame;
      const fill = i === 0 ? " animation-fill-mode: backwards;" : "";
      return `    .frame-${i} { animation: fadeInOut ${cycleDuration}s ${delay}s infinite;${fill} }`;
    })
    .join("\n");

  // Footer
  const duration = formatDuration(session.meta.stats.durationMs);
  const tStats = computeToolStats(session.scenes);
  const footerParts = [duration];
  if (tStats.responses > 0) footerParts.push(`${tStats.responses} responses`);
  if (tStats.totalTools > 0) footerParts.push(`${tStats.totalTools} tools`);
  const footerLeft = footerParts.filter(Boolean).join(" · ");
  const footerRight = opts.replayUrl ? "View full replay →" : "vibe-replay.com";

  // Build frame SVG content
  const framesSvg = frames.map((f, i) => renderFrame(f, i)).join("\n\n");

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${SVG_W}" height="${SVG_H}" viewBox="0 0 ${SVG_W} ${SVG_H}">
  <style>
    text { font-family: ${FONT}; }
    @keyframes fadeInOut {
      0% { opacity: 0 }
      ${n2(fadeIn)}% { opacity: 1 }
      ${n2(holdEnd)}% { opacity: 1 }
      ${n2(fadeOut)}% { opacity: 0 }
      100% { opacity: 0 }
    }
    .frame { opacity: 0; }
${animClasses}
  </style>

  <defs>
    <clipPath id="vr-clip-${session.meta.sessionId.slice(0, 8)}">
      <rect x="0" y="${HEADER_H}" width="${SVG_W}" height="${SVG_H - HEADER_H - FOOTER_H}"/>
    </clipPath>
  </defs>

  <!-- Background -->
  <rect width="${SVG_W}" height="${SVG_H}" rx="12" fill="${C.bg}"/>

  <!-- Header bar -->
  <path d="M0,12 Q0,0 12,0 H${SVG_W - 12} Q${SVG_W},0 ${SVG_W},12 V${HEADER_H} H0 Z" fill="${C.headerBg}"/>
  <circle cx="24" cy="${HEADER_H / 2}" r="5" fill="${C.dotRed}" opacity="0.9"/>
  <circle cx="42" cy="${HEADER_H / 2}" r="5" fill="${C.dotYellow}" opacity="0.9"/>
  <circle cx="60" cy="${HEADER_H / 2}" r="5" fill="${C.dotGreen}" opacity="0.9"/>
  <text x="${SVG_W / 2}" y="${HEADER_H / 2 + 5}" text-anchor="middle" fill="${C.dim}" font-size="12" letter-spacing="0.5">vibe-replay</text>

  <!-- Footer bar -->
  <path d="M0,${SVG_H - FOOTER_H} H${SVG_W} V${SVG_H - 12} Q${SVG_W},${SVG_H} ${SVG_W - 12},${SVG_H} H12 Q0,${SVG_H} 0,${SVG_H - 12} Z" fill="${C.headerBg}"/>
  <line x1="0" y1="${SVG_H - FOOTER_H}" x2="${SVG_W}" y2="${SVG_H - FOOTER_H}" stroke="${C.border}" stroke-width="1"/>
  <text x="${MARGIN}" y="${SVG_H - FOOTER_H / 2 + 4}" fill="${C.dim}" font-size="11">${escXml(footerLeft)}</text>
  <text x="${SVG_W - MARGIN}" y="${SVG_H - FOOTER_H / 2 + 4}" text-anchor="end" fill="${C.dim}" font-size="11">${escXml(footerRight)}</text>

  <!-- Animated content frames (clipped to content area) -->
  <g clip-path="url(#vr-clip-${session.meta.sessionId.slice(0, 8)})">
${framesSvg}
  </g>
</svg>`;
}

function renderFrame(frame: SvgFrame, index: number): string {
  const x = MARGIN;
  let y = CONTENT_TOP;
  const parts: string[] = [];

  parts.push(`  <g class="frame frame-${index}">`);

  // Section label (small uppercase)
  parts.push(
    `    <text x="${x}" y="${y}" fill="${C.dim}" font-size="11" letter-spacing="1.5">${escXml(frame.label)}</text>`,
  );
  y += 10;

  // Thin separator
  parts.push(
    `    <line x1="${x}" y1="${y}" x2="${SVG_W - x}" y2="${y}" stroke="${C.border}" stroke-width="1"/>`,
  );
  y += 28;

  // Title (user prompt) — bold blue
  parts.push(
    `    <text x="${x}" y="${y}" fill="${C.blue}" font-size="15" font-weight="600">${escXml(frame.title)}</text>`,
  );
  y += 24;

  if (frame.titleLine2) {
    parts.push(
      `    <text x="${x}" y="${y}" fill="${C.blue}" font-size="15" font-weight="600">${escXml(frame.titleLine2)}</text>`,
    );
    y += 24;
  }

  y += 12; // gap between title and detail lines

  // Detail lines
  for (const line of frame.lines) {
    if (!line.text) {
      y += 12; // blank spacer
      continue;
    }
    const weight = line.bold ? ' font-weight="600"' : "";
    parts.push(
      `    <text x="${x}" y="${y}" fill="${line.color}" font-size="13"${weight}>${escXml(line.text)}</text>`,
    );
    y += 24;
  }

  parts.push("  </g>");
  return parts.join("\n");
}

// ─── Shared helpers ────────────────────────────────────────

function collectFilesChanged(scenes: Scene[]): Map<string, number> {
  const files = new Map<string, number>();
  for (const scene of scenes) {
    if (scene.type !== "tool-call") continue;
    if (scene.toolName === "Edit" || scene.toolName === "Write") {
      const fp = scene.input.file_path;
      if (fp) {
        const name = shortPath(fp);
        files.set(name, (files.get(name) || 0) + 1);
      }
    }
  }
  return files;
}

/** Show last 2 path segments for disambiguation (avoids basename collisions) */
function shortPath(fullPath: string): string {
  const parts = fullPath.split("/");
  if (parts.length <= 2) return parts.join("/");
  return parts.slice(-2).join("/");
}

function formatDuration(ms?: number): string | null {
  if (ms == null) return null;
  const sec = Math.round(ms / 1000);
  if (sec < 60) return `${sec}s`;
  const min = Math.floor(sec / 60);
  if (min >= 60) {
    const hr = Math.floor(min / 60);
    const rm = min % 60;
    return rm > 0 ? `${hr}h ${rm}m` : `${hr}h`;
  }
  return `${min} min`;
}

/** Visual width: CJK characters count as 2, others as 1 */
function visualWidth(s: string): number {
  let w = 0;
  for (const ch of s) {
    const code = ch.codePointAt(0) || 0;
    w += isCjk(code) ? 2 : 1;
  }
  return w;
}

function isCjk(code: number): boolean {
  return (
    (code >= 0x3000 && code <= 0x9fff) || // CJK Unified + Symbols + Kana
    (code >= 0xac00 && code <= 0xd7af) || // Hangul
    (code >= 0xf900 && code <= 0xfaff) || // CJK Compatibility
    (code >= 0xff00 && code <= 0xff60) || // Fullwidth forms
    (code >= 0x20000 && code <= 0x2fa1f) // CJK Extension B–F
  );
}

/** Truncate string to fit within maxWidth visual columns */
function condenseLine(s: string, maxWidth: number): string {
  const cleaned = s.replace(/\n/g, " ").replace(/\s+/g, " ").trim();
  if (visualWidth(cleaned) <= maxWidth) return cleaned;
  // Truncate character by character
  let w = 0;
  let i = 0;
  for (const ch of cleaned) {
    const cw = isCjk(ch.codePointAt(0) || 0) ? 2 : 1;
    if (w + cw > maxWidth - 1) break;
    w += cw;
    i += ch.length;
  }
  return `${cleaned.slice(0, i)}…`;
}

/** Wrap text into 1 or 2 lines, respecting visual width */
function wrapText(s: string, maxWidth: number): [string] | [string, string] {
  const cleaned = s.replace(/\n/g, " ").replace(/\s+/g, " ").trim();
  if (visualWidth(cleaned) <= maxWidth) return [cleaned];
  // Find break point at word/CJK boundary
  let w = 0;
  let lastSpace = -1;
  let i = 0;
  for (const ch of cleaned) {
    const cw = isCjk(ch.codePointAt(0) || 0) ? 2 : 1;
    if (w + cw > maxWidth) break;
    if (ch === " ") lastSpace = i;
    w += cw;
    i += ch.length;
  }
  const breakAt = lastSpace > i * 0.3 ? lastSpace : i;
  return [cleaned.slice(0, breakAt).trim(), condenseLine(cleaned.slice(breakAt).trim(), maxWidth)];
}

function baseName(p: string): string {
  return p.split("/").pop() || p;
}

function escMd(s: string): string {
  return s.replace(/[[\]()*_`\\]/g, "\\$&");
}

function escXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/** Format a number with max 2 decimal places, stripping trailing zeros */
function n2(n: number): string {
  return Number(n.toFixed(2)).toString();
}
