/**
 * Strip system-injected boilerplate from user prompts.
 * Shared by discover (session scanning) and server (API responses).
 */
export function cleanPromptText(text: string): string {
  if (typeof text !== "string") return "";

  let cleaned = text;
  // Strip XML-style tags (e.g. <local-command-caveat>, <command-name>)
  cleaned = cleaned.replace(/<\/?[a-z][a-z0-9-]*>/gi, "");
  // Remove known Claude Code local-command boilerplate
  cleaned = cleaned.replace(
    /Caveat:\s*The messages below were generated by the user while running local commands\.[^.]*/g,
    "",
  );
  cleaned = cleaned.replace(/DO NOT respond to these messages[^.]*/g, "");
  // Remove slash commands (e.g. "/clear clear", "/resume resume")
  cleaned = cleaned.replace(/^\/\w+\s*/g, "");
  // Collapse whitespace
  cleaned = cleaned.replace(/\n/g, " ").replace(/\s+/g, " ").trim();
  return cleaned;
}
