/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        terminal: {
          bg: "var(--bg)",
          surface: "var(--surface)",
          "surface-hover": "var(--surface-hover)",
          "surface-2": "var(--surface-2)",
          "surface-inset": "var(--surface-inset)",
          border: "var(--border)",
          "border-subtle": "var(--border-subtle)",
          text: "var(--text)",
          dim: "var(--dim)",
          dimmer: "var(--dimmer)",
          green: "var(--green)",
          "green-subtle": "var(--green-subtle)",
          "green-emphasis": "var(--green-emphasis)",
          blue: "var(--blue)",
          "blue-subtle": "var(--blue-subtle)",
          "blue-emphasis": "var(--blue-emphasis)",
          orange: "var(--orange)",
          "orange-subtle": "var(--orange-subtle)",
          "orange-emphasis": "var(--orange-emphasis)",
          sienna: "var(--sienna)",
          "sienna-subtle": "var(--sienna-subtle)",
          "sienna-emphasis": "var(--sienna-emphasis)",
          yellow: "var(--yellow)",
          "yellow-subtle": "var(--yellow-subtle)",
          "yellow-emphasis": "var(--yellow-emphasis)",
          red: "var(--red)",
          "red-subtle": "var(--red-subtle)",
          "red-emphasis": "var(--red-emphasis)",
          purple: "var(--purple)",
          "purple-subtle": "var(--purple-subtle)",
          "purple-emphasis": "var(--purple-emphasis)",
          cyan: "var(--cyan)",
          "cyan-subtle": "var(--cyan-subtle)",
          "cyan-emphasis": "var(--cyan-emphasis)",
          user: "var(--accent-user)",
          "user-subtle": "var(--accent-user-subtle)",
          "user-emphasis": "var(--accent-user-emphasis)",
          response: "var(--accent-response)",
          "response-subtle": "var(--accent-response-subtle)",
          "response-emphasis": "var(--accent-response-emphasis)",
          tool: "var(--accent-tool)",
          "tool-subtle": "var(--accent-tool-subtle)",
          "tool-emphasis": "var(--accent-tool-emphasis)",
          context: "var(--accent-context)",
          "context-subtle": "var(--accent-context-subtle)",
          "context-emphasis": "var(--accent-context-emphasis)",
          thinking: "var(--accent-thinking)",
          "thinking-subtle": "var(--accent-thinking-subtle)",
          "thinking-emphasis": "var(--accent-thinking-emphasis)",
          error: "var(--accent-error)",
          "error-subtle": "var(--accent-error-subtle)",
          "error-emphasis": "var(--accent-error-emphasis)",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
      },
      boxShadow: {
        "layer-sm": "var(--shadow-sm)",
        "layer-md": "var(--shadow-md)",
        "layer-lg": "var(--shadow-lg)",
        "layer-xl": "var(--shadow-xl)",
      },
      transitionTimingFunction: {
        material: "cubic-bezier(0.4, 0, 0.2, 1)",
        "material-decel": "cubic-bezier(0.0, 0, 0.2, 1)",
        "material-accel": "cubic-bezier(0.4, 0, 1, 1)",
      },
    },
  },
  plugins: [],
};
