import type { SessionSummary, SourceSession } from "../types";

// ─── Shared types ────────────────────────────────────────────────────

export type CachedListResponse<T> = {
  sessions: T[];
  cachedAt?: string;
};

export interface SourcesEnrichmentStatus {
  running: boolean;
  processed: number;
  total: number;
  updated: number;
  startedAt?: string;
  finishedAt?: string;
  message?: string;
}

// ─── Cache helpers ───────────────────────────────────────────────────

export const CACHE_REFRESH_TTL_MS = 5 * 60 * 1000;

export function parseCachedList<T>(payload: unknown): CachedListResponse<T> | null {
  if (!payload || typeof payload !== "object") return null;
  const obj = payload as { sessions?: unknown; cachedAt?: unknown };
  if (!Array.isArray(obj.sessions)) return null;
  return {
    sessions: obj.sessions as T[],
    cachedAt: typeof obj.cachedAt === "string" ? obj.cachedAt : undefined,
  };
}

export function isCacheFresh(iso?: string, ttlMs = CACHE_REFRESH_TTL_MS): boolean {
  if (!iso) return false;
  const ageMs = Date.now() - new Date(iso).getTime();
  return Number.isFinite(ageMs) && ageMs >= 0 && ageMs < ttlMs;
}

// ─── Formatting helpers ──────────────────────────────────────────────

export function formatCacheAge(iso?: string): string {
  if (!iso) return "just now";
  const ageMs = Date.now() - new Date(iso).getTime();
  if (!Number.isFinite(ageMs) || ageMs < 0) return "just now";
  const mins = Math.floor(ageMs / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}

export function formatCompactAge(iso?: string, nowMs = Date.now()): string {
  if (!iso) return "";
  const ageMs = nowMs - new Date(iso).getTime();
  if (!Number.isFinite(ageMs) || ageMs < 0) return "0m";
  const mins = Math.floor(ageMs / 60000);
  if (mins < 60) return `${mins}m`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h`;
  const days = Math.floor(hours / 24);
  return `${days}d`;
}

export function formatDate(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });
}

export function formatCost(cost?: number): string {
  if (!cost) return "";
  return `$${cost.toFixed(2)}`;
}

export function formatSize(bytes: number): string {
  const kb = Math.round(bytes / 1024);
  return kb >= 1024 ? `${(kb / 1024).toFixed(1)}MB` : `${kb}KB`;
}

export function timeAgo(iso: string): string {
  const ms = Date.now() - new Date(iso).getTime();
  const mins = Math.floor(ms / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  if (days < 30) return `${days}d ago`;
  return formatDate(iso);
}

export function projectName(project: string): string {
  const parts = project.replace(/\/$/, "").split("/");
  return parts[parts.length - 1] || project;
}

// ─── Text helpers ────────────────────────────────────────────────────

export const TITLE_MAX_CHARS = 120;

export function normalizeTitleText(value?: string): string {
  return (value || "").replace(/\s+/g, " ").trim().slice(0, TITLE_MAX_CHARS);
}

/** Strip system-injected noise from first prompt for display */
export function cleanPrompt(text: string): string {
  let cleaned = text;
  cleaned = cleaned.replace(/<\/?[a-z][a-z0-9-]*>/gi, "");
  cleaned = cleaned.replace(
    /Caveat:\s*The messages below were generated by the user while running local commands\.[^.]*/g,
    "",
  );
  cleaned = cleaned.replace(/DO NOT respond to these messages[^.]*/g, "");
  cleaned = cleaned.replace(/!\[AI Session:[^\]]*]\([^)]+\)/gi, "");
  cleaned = cleaned.replace(/###\s*AI Coding Session[^\n]*/gi, "");
  cleaned = cleaned.replace(/\d+\s+prompts?,\s+\d+\s+tools?,[^\n]*/gi, "");
  cleaned = cleaned.replace(/^\/\w+\s*/g, "");
  cleaned = cleaned.replace(/\s+/g, " ").trim();
  return cleaned;
}

export function sourceSuggestedTitle(s: SourceSession): string {
  const explicitTitle = s.title ? normalizeTitleText(cleanPrompt(s.title)) : "";
  if (explicitTitle) return explicitTitle;
  const promptCandidates = [...(s.prompts || []), s.firstPrompt];
  for (const candidate of promptCandidates) {
    const cleaned = normalizeTitleText(cleanPrompt(candidate || ""));
    if (cleaned) return cleaned;
  }
  return s.slug;
}

export function replaySuggestedTitle(s: SessionSummary): string {
  const explicitTitle = normalizeTitleText(s.title);
  if (explicitTitle) return explicitTitle;
  const firstMessage = normalizeTitleText(s.firstMessage);
  if (firstMessage) return firstMessage;
  const firstFromMessages = normalizeTitleText(s.messages?.[0]);
  if (firstFromMessages) return firstFromMessages;
  return s.slug;
}

// ─── Navigation ──────────────────────────────────────────────────────

export function navigateTo(
  params: Record<string, string | null>,
  options: { replace?: boolean } = {},
) {
  const url = new URL(window.location.href);
  const DASHBOARD_PARAMS = ["tab", "project", "q", "archived"];

  // 1. If we are currently on dashboard, capture its state to sessionStorage
  const isCurrentlyDashboard =
    url.searchParams.get("view") === "dashboard" || !url.searchParams.has("session");
  if (isCurrentlyDashboard) {
    const dashboardState: Record<string, string> = {};
    DASHBOARD_PARAMS.forEach((p) => {
      const v = url.searchParams.get(p);
      if (v) dashboardState[p] = v;
    });
    if (Object.keys(dashboardState).length > 0) {
      sessionStorage.setItem("vibe_dashboard_state", JSON.stringify(dashboardState));
    }
  }

  // 2. If we are entering a session, remove dashboard params from URL
  if (params.session) {
    DASHBOARD_PARAMS.forEach((p) => {
      if (params[p] === undefined) {
        url.searchParams.delete(p);
      }
    });
    // Also remove 'view' if we are going to a session
    if (params.view === undefined) {
      url.searchParams.delete("view");
    }
  }

  // 3. If we are going back to dashboard, restored saved state if URL is empty
  const goingToDashboard = params.view === "dashboard" || (params.session === null && !params.view);
  if (goingToDashboard) {
    const saved = sessionStorage.getItem("vibe_dashboard_state");
    if (saved) {
      try {
        const state = JSON.parse(saved);
        Object.entries(state).forEach(([k, v]) => {
          if (params[k] === undefined && !url.searchParams.has(k)) {
            url.searchParams.set(k, v as string);
          }
        });
      } catch (e) {
        console.error("Failed to restore dashboard state", e);
      }
    }
    // Clean up viewer params when going back to dashboard
    url.searchParams.delete("v");
  }

  for (const [key, value] of Object.entries(params)) {
    if (value === null) url.searchParams.delete(key);
    else url.searchParams.set(key, value);
  }
  if (options.replace) {
    window.history.replaceState({}, "", url.toString());
  } else {
    window.history.pushState({}, "", url.toString());
  }
  window.dispatchEvent(new PopStateEvent("popstate"));
}

// ─── Shared UI components ────────────────────────────────────────────

// ─── Shared UI helpers ────────────────────────────────────────────────

export const PROVIDER_BADGE_COLORS: Record<string, string> = {
  "claude-code": "bg-terminal-orange-subtle text-terminal-orange",
  cursor: "bg-terminal-blue-subtle text-terminal-blue",
};

export function providerBadgeLabel(provider: string): string {
  return provider === "claude-code" ? "Claude" : provider === "cursor" ? "Cursor" : provider;
}

export function providerBadgeClass(provider: string): string {
  return PROVIDER_BADGE_COLORS[provider] || "bg-terminal-surface text-terminal-dim";
}

export function getErrorMessage(err: unknown): string {
  if (err instanceof Error) return err.message;
  if (typeof err === "string") return err;
  return "Unknown error";
}

/** Shorten a path to fit the sidebar, keeping first + last meaningful segments */
export function shortenPath(path: string): string {
  const MAX = 26;
  if (path.length <= MAX) return path;
  const parts = path.split("/");
  if (parts.length <= 2) return path;
  const first = parts[0];
  const lastTwo = parts.slice(-2).join("/");
  const candidate = `${first}/\u2026/${lastTwo}`;
  if (candidate.length <= MAX) return candidate;
  const last = parts[parts.length - 1];
  return `${first}/\u2026/${last}`;
}

export function computeProjectLabels(projects: string[]): Map<string, string> {
  const labels = new Map<string, string>();
  for (const p of projects) {
    labels.set(p, shortenPath(p));
  }
  return labels;
}
